# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.stylua]
command = "stylua"
options = [ "--config-path", "./.formatters/stylua.toml" ]
includes = [ "*.lua" ]
excludes = []

[formatter.statix]
command = "statix"
options = [ "--config", "./.formatters/statix.toml" ]
includes = [ ".nix" ]

[formatter.deadnix]
command = "deadnix"
includes = [ ".nix" ]

[formatters.nixpkgs-fmt]
command = "nixpkgs-fmt"
includes = [ ".nix" ]
