{
  imports = [
    ./atuin.nix
    ./bash.nix
    # ./craftos-pc
    ./desktop-standalone-packages.nix
    ./dircolors.nix
    ./direnv.nix
    ./eza.nix
    ./fd.nix
    ./fonts.nix
    ./gh.nix
    ./git.nix
    ./gpg.nix
    ./h.nix
    ./helix.nix
    ./home-manager.nix
    ./librewolf
    ./nixpkgs
    ./nnn.nix
    ./nvim
    ./readline.nix
    ./ripgrep.nix
    ./shell-standalone-packages.nix
    ./starship.nix
    ./syncthing.nix
    ./zoxide.nix
    ./zsh
  ];
}
