[helpers]

[default]
depends = [
	"emacs",
	"gem",
	"bat",
	"git",
	"micro",
	"neofetch",
	"nvim",
	"rvm",
	"ripgrep",
	"zsh"
]

[linux]
depends = [
	"default",
	"gnome-terminal",
	"albert"
]

[nvim]
depends = []
[nvim.files]
nvim = { target = "~/.config/nvim", type = "symbolic", recurse=false }

[git]
depends = []
[git.files]
"git/config" = "~/.gitconfig"

[zsh]
[zsh.files]
"zsh/config" = { target = "~/.zsh", type = "symbolic", recurse=false }
"zsh/config/init.zsh" = "~/.zshrc"
"zsh/config/zprofile.zsh" = "~/.zprofile"
"zsh/zplug" = { target = "~/.zplug", type = "symbolic", recurse=false }

[ruby]
depends = []

[gem]
depends = ["ruby"]
[gem.files]
"ruby/gemrc.yaml" = "~/.gemrc"

[rvm]
depends = ["ruby"]
[rvm.files]
"ruby/rvmrc" = "~/.rvmrc"

[node]
depends = []

[npm]
depends = ["node"]
[npm.files]
"node/npmrc" = "~/.npmrc"

[micro]
[micro.files]
micro = { target = "~/.config/micro", type = "symbolic", recurse=false }

[neofetch]
[neofetch.files]
neofetch = "~/.config/neofetch"

[emacs]
[emacs.files]
"emacs/emacs.d" = { target = "~/.emacs.d", type = "symbolic", recurse=false}
"emacs/dotspacemacs" = "~/.spacemacs"

[gnome-terminal]
depends = []
# We have this so that we can check if the user wants to have a GNOME Terminal configuration
# See .dotter/pre_deploy.sh for implementation

[albert]
[albert.files]
"albert/albert.conf" = "~/.config/albert/albert.conf"

[bat]
[bat.files]
"bat" = "~/.config/bat"

[ripgrep]
[ripgrep.files]
"ripgrep" = "~/.config/ripgrep"
