name: Checks
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2 # failsafe in case stuff starts to download; it should take much longer than 2 minutes to fully download everything
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Run `just ci`
        run: |
          nix develop .#ci --command sh -c "just ci"
